// Tenant
export const tenantKey = "tenant"
export const loginsPerSpKey = "logins_per_sp"
export const loginsPerIdpKey = "logins_per_idp"
export const loginsPerCountryKey = "logins_per_country"
export const loginsGroupByDayKey = "logins_groupby/day"
export const registeredUsersCountByKey = "registered_users_countby"
export const spsKey = "sps"
export const idpsKey = "idps"
export const communitiesKey = "communities"
export const countryStatsByVoKey = "country_stats_by_vo"
export const communitiesGroupByKey = "communities_groupby"